# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with flake8
        run: |
          pip3 install -r requirements-dev.txt
          # Stop the build if there are Python syntax errors, undefined names or unused imports etc.
          flake8
          # Do not stop the build, but indicate room for improvement.
          # exit-zero treats all errors as warnings.
          flake8 . --exit-zero --ignore= --select=
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      #- name: Typilus, Suggest Python Type Annotations
      #  uses: typilus/typilus-action@v0.9
      - name: Run unittests
        id: unittests
        continue-on-error: true
        env:
          CONNECTION_METHOD: ${{ secrets.CONNECTION_METHOD }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
        run: |
          coverage run -m unittest -v test_module.TestScholarly
      - name: Generate coverage report (macOS only)
        if:
          "matrix.os == 'macos-latest'"
        run: |
          curl --data-binary @.github/.codecov.yml https://codecov.io/validate | head -n 1
          coverage xml
      - name: Upload code coverage (macOS only)
        if:
          "matrix.os == 'macos-latest'"
        uses: codecov/codecov-action@v2
        with:
          directory: ./
          fail_ci_if_error: false
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
      - name: Check if unittests failed
        if: "steps.unittests.outcome == 'failure'"
        run: exit 1
